### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by TheAnnoyingFruit** [Curve/gpu-screen-recorder-all-audio#1]
On arch building this fails with this error:
gpu-screen-recorder-all-audio/src/main.cpp:4:10: fatal error: rohrkabel/loop/main.hpp: No such file or directory
    4 | #include <rohrkabel/loop/main.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/gpu-screen-recorder-all-audio.dir/build.make:76: CMakeFiles/gpu-screen-recorder-all-audio.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:240: CMakeFiles/gpu-screen-recorder-all-audio.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
|
If this builds fine for you what distro are you using so I can understand the differences or just build in that distro.

**Comment by Curve** [comment]
There've been some upstream changes to rohrkabel so I'll have to update this project.

I'm currently fairly busy but will try to get it done til next week :)

**Comment by TheAnnoyingFruit** [comment]
Take all the time you need. Appreciate the very quick response

**Comment by TheAnnoyingFruit** [comment]
Has any free time came up? I haven't been able to find another solution that uses the command line and mixes the audio.

**Comment by dec05eba** [comment]
If you just want to mix desktop audio and microphone then you can use the -a "default_output|default_input" option

**Comment by TheAnnoyingFruit** [comment]
> If you just want to mix desktop audio and microphone then you can use the -a "default_output|default_input" option

I will try this thank you

**Comment by Curve** [comment]
> Has any free time came up? I haven't been able to find another solution that uses the command line and mixes the audio.

Sorry I totally forgot about this :'D
You may want to checkout [venmic](https://github.com/Vencord/venmic) - this is something I've developed for discord screen sharing, and in essence it can do everything this project does and more.

You can compile and start venmic as a server and send a simple HTTP Request to start entire system audio capture, a new node named "vencord-screen-share" will be created :)

**Comment by Curve** [comment]
> > Has any free time came up? I haven't been able to find another solution that uses the command line and mixes the audio.
> 
> Sorry I totally forgot about this :'D
> You may want to checkout [venmic](https://github.com/Vencord/venmic) - this is something I've developed for discord screen sharing, and in essence it can do everything this project does and more.
> 
> You can compile and start venmic as a server and send a simple HTTP Request to start entire system audio capture, a new node named "vencord-screen-share" will be created :)

The HTTP requests are documented in the projects readme
